openapi: '3.0.2'
info:
  title: Vaika API
  version: latest
servers:
  - url: https://nj6ruxnfui.execute-api.eu-west-3.amazonaws.com/Prod

paths:
  /ping:
    get:
      tags:
        - Health
      summary: Ping pong Health endpoint
      operationId: pingPong
      responses:
        '200':
          description: pong
          content:
            text/plain:
              schema:
                type: string
                example: pong
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'

  /whoami:
    get:
      security:
        - bearerAuth: []
      tags:
        - Security
      summary: Who am I? Tells you who you are.
      operationId: whoami
      responses:
        '200':
          description: Who you are
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Whoami'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'

  /login:
    post:
      tags:
        - Security
      summary: Log in to access the dashboard
      operationId: login
      requestBody:
        required: true
        description: Email & Password
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: user@example.com
                password:
                  type: string
      responses:
        '200':
          description: The JWT token for the user
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          $ref: '#/components/responses/400'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

  responses:
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BadRequestException'
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NotAuthorizedException'
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ResourceNotFoundException'
    '429':
      description: Too many requests to the API
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TooManyRequestsException'
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InternalServerException'

  schemas:
    UserBase:
      properties:
        id:
          type: string
        username:
          type: string
          example: Don_Dada
    Whoami:
      allOf:
        - $ref: '#/components/schemas/UserBase'
      properties:
        bearer:
          type: string
    User:
      allOf:
        - $ref: '#/components/schemas/UserBase'
      properties:
        email:
          type: string
          example: user@example.com
    CrupdateUser:
      allOf:
        - $ref: '#/components/schemas/User'
      properties:
        password:
          type: string
    Brand:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
          example:
            - 'Mercedes'
            - 'Mazda'
    Type:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
          example:
            - 'SUV'
            - 'Classic'
    MotorType:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
          example:
            - 'Diesel'
            - 'Hybrid'
    Image:
      type: object
      properties:
        id:
          type: string
        url:
          type: string
        car_id:
          type: string
    CarBase:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
          example: 'Adventure Van'
        description:
          type: string
        price:
          type: number
          example: 30000
        model:
          type: string
          example: 'Sprinter'
        color:
          type: string
          example: 'White'
        power:
          type: string
          example: '188hp'
        place_number:
          type: number
          example: 22
    Car:
      allOf:
        - $ref: '#/components/schemas/CarBase'
      properties:
        brand:
          $ref: '#/components/schemas/Brand'
        type:
          $ref: '#/components/schemas/Type'
        motor_type:
          $ref: '#/components/schemas/MotorType'
        images:
          type: array
          items:
            $ref: '#/components/schemas/Image'
    CrupdateCar:
      allOf:
        - $ref: '#/components/schemas/CarBase'
      properties:
        brand_id:
          type: string
        type_id:
          type: string
        motor_type_id:
          type: string
    AppointmentBase:
      type: object
      properties:
        id:
          type: string
        last_name:
          type: string
          example: Andrianarisoa
        first_name:
          type: string
          example: Hajatiana
        email:
          type: string
          example: user@example.com
        contact:
          type: string
          example: '+261344444444'
        message:
          type: string
          example: Hello ! Wanna grab that car !!!
        appointment_datetime:
          type: string
          format: date-time
    AppointmentStatusEnum:
      type: string
      enum:
        - PENDING
        - VALIDATED
        - REJECTED
        - ARCHIVED
    Appointment:
      allOf:
        - $ref: '#/components/schemas/AppointmentBase'
      properties:
        car:
          $ref: '#/components/schemas/Car'
        status:
          $ref: '#/components/schemas/AppointmentStatusEnum'
    CrupdateAppointment:
      allOf:
        - $ref: '#/components/schemas/AppointmentBase'
      properties:
        car_id:
          type: string

    #Exceptions

    Exception:
      type: object
      properties:
        type:
          type: string
        message:
          type: string
    BadRequestException:
      allOf:
        - $ref: '#/components/schemas/Exception'
      example:
        type: BadRequestException
        message: Bad request
    NotAuthorizedException:
      allOf:
        - $ref: '#/components/schemas/Exception'
      example:
        type: NotAuthorizedException
        message: Not authorized
    ResourceNotFoundException:
      allOf:
        - $ref: '#/components/schemas/Exception'
      example:
        type: ResourceNotFoundException
        message: Resource of type <T> identified by <I> not found
    TooManyRequestsException:
      allOf:
        - $ref: '#/components/schemas/Exception'
      example:
        type: TooManyRequestsException
        message: Too many requests
    InternalServerException:
      allOf:
        - $ref: '#/components/schemas/Exception'
      example:
        type: InternalServerException
        message: Unexpected error
