name: Publish client

on:
  workflow_dispatch:

jobs:
  release-version:
    uses: ./.github/workflows/release-version.yml
    secrets: inherit

  publish-to-npm-registry:
    runs-on: ubuntu-latest

    needs: release-version

    env:
      AWS_REGION: eu-west-3

    steps:
      ###############################################################
      ########## GENERATE AND PUBLISH TYPESCRIPT CLIENT #############
      ###############################################################

      - uses: actions/checkout@v4.1.1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "corretto"

      - name: Read gradle.properties file
        id: extract_version
        run: |
          version=$(grep -oP 'version=\K[^ ]+' gradle.properties)
          echo "::set-output name=version::$version"

      - name: Generate typescript client
        run: ./gradlew generateTsClient -Pargs=${{ steps.extract_version.outputs.version }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 17.x
          registry-url: "https://registry.npmjs.org"

      - name: Publish Typescript client
        run: |
          cd build/gen-ts/
          sed -i "s/\"https:\/\/https://nj6ruxnfui.execute-api.eu-west-3.amazonaws.com/Prod\"/\(process.env.NEXT_APP_API_URL || \"\"\)/g" base.ts
          sed -i "s/\"dependencies\"/\"peerDependencies\"/g" package.json
          sed -i '11d' tsconfig.json && sed -i "s/\"es6\",/\"es6\",\"DOM\"/g" tsconfig.json
          echo -e "\n*.ts\nnode_module\n!*.d.ts\n.idea\n.vscode\n.openapi-generator\n.openapi-generator-ignore\ngit_push.sh" >> .npmignore
          npm config set always-auth true
          npm install
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
